#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel1,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel1,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     leftLift,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     rightLift,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     leftWheel2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightWheel2,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
task main()
{
	nMotorEncoder[leftWheel1] = 0;
	nMotorEncoder[rightWheel1] = 0;
	while(true) {
		getJoystickSettings(joystick);
		if(joy1Btn(Btn1)){
			motor[leftWheel1] = 10;
			motor[rightWheel1] = -15;
			motor[leftWheel2] = 10;
			motor[rightWheel2] = -15;
			} else if (joy1Btn(Btn3)) {
			motor[leftWheel1] = -10;
			motor[rightWheel1] = 15;
			motor[leftWheel2] = -10;
			motor[rightWheel2] = 15;
			} else {
			motor[leftWheel1] = 0;
			motor[rightWheel1] = 0;
			motor[leftWheel2] = 0;
			motor[rightWheel2] = 0;
			}
		displayCenteredTextLine(1, "%d, %d", nMotorEncoder[leftWheel1], nMotorEncoder[rightWheel1]);
	}
}
