#pragma config(Motor,  motorA,          winch,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
task main()
{
if(joy1Btn(Btn1))
	motor[winch] = 100;
if(joy1Btn(Btn2))
	motor[winch] = -100;
}
