#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     leftLift,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     rightLift,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     leftWheel2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightWheel2,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
///////////// Harvard-Westlake Middle School Robotics Team              /////////////
///////////// FTC7155                                                   /////////////
///////////// Tele-Op Code                                           	/////////////
/////////////                                                           /////////////
///////////// Authors:  Jonathan Damico, Nomi Ringoach, Sebastian Ko    /////////////
/////////////           Jack Reily, Alex Kahn                           /////////////
///////////// Version:  1                                               /////////////
///////////// Since:    November 3, 2014                                /////////////
///////////// Revised:  December 1, 2014                                /////////////
/////////////															/////////////
///////////// View All of our code at http://github.com/ftc7155/2015	/////////////
/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

//Include Drivers
#include "JoystickDriver.c" 				//Include the files to make the robot drivable by a joystick
#include "drivers/hitechnic-sensormux.h"	//Include Sensor Multiplexer Drivers

//Used to Initialize Sensors Plugged Into Sensor Multiplexer - Currently Unused
const tMUXSensor leftIR = msensor_S3_3;		//Initialize the Left IR Sensor
const tMUXSensor rightIR = msensor_S3_1;	//Initialize the Right IR Sensor
const tMUXSensor touch = msensor_S3_2;		//Initialize the Touch Sensor

//Task to control all the movement of the hook for the robot during tele-op
task hook () {

	//Boolean statement to determine if the hook is up. Initilization.
	bool hookUp = false;

	//Loop this part of the code forever
	while(true) {

		//Update the Joysticks
		getJoystickSettings(joystick);

		//Put hook up
		if(joy1Btn(Btn2)&&!hookUp) { 	//If the A Button is pressed, and the hook isn't up
			servo[leftHook]=155;		//Set left hook to up position
			servo[rightHook]=65;		//Set right hook to up position
			hookUp=true;				//Tell the program that the hook is up
			wait1Msec(300);				//Wait so that we can give the hook time to go up, and so the button doesn't get "stuck"
		}

		//Put hook down
		if(joy1Btn(Btn2)&&hookUp) {		//If the A Button is pressed, and the hook is up
			servo[leftHook]=50;			//Set left hook to down position
			servo[rightHook]=173;		//Set left hook to down position
			hookUp=false;				//Tell the program that the hook is down
			wait1Msec(300);				//Wait so that we can give the hook time to go up, and so the button doesn't get "stuck"
		}
	}
}


//Task to control the intake on the robot
task intake () {

	//Boolean statement, telling us if the intake is spinning
	bool intakeOn = false;

	//Loop for all of atonomous
	while(true) {

		//Get the joystick positions
		getJoystickSettings(joystick);

		//Take In Balls
		if(joy1Btn(Btn6) && !intakeOn){ 							//If the intake in button is pressed, and the intake is off
			motor[leftIntake] = 127;								//Set the left intake motor to full power, to rake in balls
			motor[rightIntake] = 127;								//Set the right intake motor to full power, to rake in balls
			intakeOn = true;										//Tell the program that the intake is on
			wait1Msec(300);											//Wait so that the program doesn't get stuck, and to give time for the intake to rake in balls
		} 

		//Spit Out Balls
		else if(joy1Btn(Btn8) && !intakeOn) {						//If the intake out button is pressed, and the intake is off
			motor[leftIntake] = -50;								//Set the left intake motor to half power, to accuratley spit out balls without having them fall out
			motor[rightIntake] = -50;								//Set the right intake motor to half power, to accuratley spit out balls without having them fall out
			intakeOn = true;										//Tell the program that the intake is on
			wait1Msec(300);											//Wait so that the program doesn't get stuck, and to give time for the intake to rake in balls
		} 

		//Stop Intake Movement
		else if (intakeOn && (joy1Btn(Btn8) || joy1Btn(Btn6))) {	//If any intake button is pressed, and the intake is on
			motor[leftIntake] = 0;									//Stop the intake
			motor[rightIntake] = 0;									//Stop the intake
			intakeOn = false;										//Tell the program that the intake is off
			wait1Msec(300);											//Wait so that the program doesn't get stuck, and to give time for the intake to rake in balls
		}
	}
}

//Main task for code
task main() {

	/*
	* Before start of autonomous:
	* Move lifts all the way down, manually
	* Carefully place robot on ramp
	*/

	//Wait for Start of Autonomous
	waitForStart();

	//Set Lift Encoders
	nMotorEncoder[leftLift] = 0;	//Set Left Lift Encoder to 0
	nMotorEncoder[rightLift] = 0;	//Set Left Lift Encoder to 0

	//Start tasks for differient parts of the robot
	startTask(intake);	//Start task for the intake on the linear lifts
	startTask(hook);	//Start task for the hook on the back of the robot

	//Loop for all of atonomous
	while(true) {

		//Get joytick settings and positions
		getJoystickSettings(joystick);


		//Set Left Wheels to Joystck Positions
		motor[leftWheel1] = joystick.joy1_y1;	//Set Back Left Wheel Speeds to Joystick Position
		motor[leftWheel2] = joystick.joy1_y1;	//Set Front Left Wheel Speeds to Joystick Position

		//Set Right Wheels to Joystick Positions
		motor[rightWheel1] = joystick.joy1_y2;	//Set Back Right Wheel Speeds to Joystick Positions
		motor[rightWheel2] = joystick.joy1_y2;	//Set Front Right Wheel Speeds to Joystick Positions

		//Controls Upward Motion of Lift
		if(joy1Btn(Btn5)&& nMotorEncoder[leftLift]>-3700){				//If the up button is pressed, and the lift is within the safe use limits
			motor[leftLift]=-127;										//Set the Left Lift Motors to Full Power, Upwards
			motor[rightLift]=127;										//Set the Right Lift Motors to Full Power, Upwards
		} 

		//Controls Downward Motion of Lift
		else if(joy1Btn(Btn7) && nMotorEncoder[leftLift]<-10){			//If the down button is pressed, and the lift is within the safe use limits
			motor[leftLift]=100;										//Set the Left Lift Motors to ~75% Power, Downwards
			motor[rightLift]=-100;										//Set the Right Lift Motors to ~75% Power, Downwards
		} 

		//Makes Sure that the Lift Stops Moving when No Buttons are Pressed
		else {															//If no lift buttons are pressed
			motor[leftLift] = 0;										//Stop Lift Motion
			motor[rightLift] = 0;										//Stop Lift Motion
		}

		//Used for debugging
		displayCenteredBigTextLine(1, "%d, %d", nMotorEncoder[leftLift], nMotorEncoder[rightLift]);	//Display the encoder values of the left and right wheels
	}
}
