#pragma config(Hubs,  S1, HTServo,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          rightIntake,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftIntake,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     leftLift,      tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     rightLift,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     leftWheel2,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_2,     rightWheel2,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    rightHook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    leftHook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////
///////////// Harvard-Westlake Middle School Robotics Team              /////////////
///////////// FTC7155                                                   /////////////
///////////// Autonomous Code                                           /////////////
/////////////                                                           /////////////
///////////// Authors:  Jonathan Damico, Nomi Ringoach, Sebastian Ko    /////////////
/////////////           Jack Reily, Alex Kahn                           /////////////
///////////// Version:  1                                               /////////////
///////////// Since:    November 3, 2014                                /////////////
///////////// Revised:  December 1, 2014                                /////////////
/////////////															/////////////
///////////// View All of our code at http://github.com/ftc7155/2015	/////////////
/////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

//Get Rid of "Unused" Warnings
#pragma systemFile

//Include Drivers
#include "drivers/hitechnic-sensormux.h"	//Include Sensor Multiplexer Drivers
#include "drivers/hitechnic-irseeker-v2.h"	//Include IR Sensor Dirvers

//Used to Initialize Sensors Plugged Into Sensor Multiplexer - Currently Unused
const tMUXSensor leftIR = msensor_S3_3;		//Initialize the Left IR Sensor
const tMUXSensor rightIR = msensor_S3_1;	//Initialize the Right IR Sensor
const tMUXSensor touch = msensor_S3_2;		//Initialize the Touch Sensor

/////////////////////////////////////////////////////////////////////////////////////////
/////									AUTO SETUP									/////
/////////////////////////////////////////////////////////////////////////////////////////
/////Change this depending if the robot is starting on the ramp or on the ground.	/////
/* */bool startOnRamp = true;														/////
/////																				/////
/////Use this if we want to knock down the cascade.									/////
/* */bool knockDownCascade = true;													/////
/////																				/////
/////Set True if we want to score a goal.											/////
/* */bool scoreInGoal = true;														/////
/////////////////////////////////////////////////////////////////////////////////////////

//Recursion
int leftHistory[1], rightHistory[1], numberOfSteps, changeInTime;

//Converts meters to an encoder value
//Unused
float toEncoderValues (float inches){
	inches*=90;
	return(inches);
}

//Sets all of the left wheels to a value
void setAllLeftMotors (int speed) {
	motor[leftWheel1] = speed;
	motor[leftWheel2] = speed;
}

//Sets all of the right wheels to a value
void setAllRightMotors (int speed) {
	motor[rightWheel1] = speed;
	motor[rightWheel2] = speed;
}

//Sets all of the wheels to a value
void setAllMotors(int speed) {
	setAllLeftMotors(speed);
	setAllRightMotors(speed);
}

//Sets all of the left wheels encoders to a value
void setAllLeftMotorEncoders (float encoderValue) {
	nMotorEncoder[leftWheel1] = encoderValue;
	nMotorEncoder[leftWheel2] = encoderValue;
}

//Sets all of the right wheel encoders to a value
void setAllRightMotorEncoders (float encoderValue) {
	nMotorEncoder[rightWheel1] = encoderValue;
	nMotorEncoder[rightWheel2] = encoderValue;
}

//Sets all of the base encoders to a value
void setAllMotorEncoders(float encoderValue) {
	setAllLeftMotorEncoders(encoderValue);
	setAllRightMotorEncoders(encoderValue);
}

//Sets all of the base encoders to a value
void setAllMotorEncoderTargets(int target) {
	nMotorEncoderTarget[rightWheel1] = target;
	nMotorEncoderTarget[leftWheel1] = target;
}

//Sets both sides of lift motors to the desired speed
void setAllLiftMotors (float speed) {
	motor[leftLift]=-speed;
	motor[rightLift]=speed;
}

//Sets All the Lift Motor Encoder Targets
void setAllLiftMotorEncoderTargets (int value) {
	nMotorEncoderTarget[leftLift] = value;
	nMotorEncoderTarget[rightLift] = value;
}

//The Backbone of Autonomous
task main() {
	nMotorEncoder[leftLift] = 0;				//Set the Lift Motor Encoder Values to 0
	nMotorEncoder[rightLift] = 0;				//Set the Lift Motor Encoder Values to 0
	while(nMotorEncoder[leftLift]>-300)			//While the Motors haven't reached their target,
		setAllLiftMotors(127);					//Move the lift up
	setAllLiftMotors(0);						//Stop lift motion after it have been raised to the desired height
	motor[leftIntake] = 20;						//Set the left intake motors to 20, to constantly keep the preloaded atonomous balls inside of the intake
	motor[rightIntake] = 20;					//Set the right intake motors to 20, to constantly keep the preloaded atonomous balls inside of the intake
	setAllMotors(127);							//Move at full speed forward, to drive off of the ramp in autonomous
	wait1Msec(1500);							//Wait until the robot is off the ramp
	setAllMotors(50);							//Slow down a bit, so the robot doesn't make any harsh movements to throw it off track
	wait1Msec(200);								//Wait so the robot can slow down
	setAllMotors(0);							//Stop the motors, so we can raise the lift
	while(nMotorEncoder[leftLift]>-3100)		//While the lift is not as high as the goal
		setAllLiftMotors(127);					//Move the lift up
	setAllLiftMotors(0);						//Stop lift motion after it has been raised to the desired height
	setAllMotors(20);							//Drive forward to the goal
	wait1Msec(700);								//Wait until we're up against the goal
	setAllMotors(0);							//Stop Movement
	motor[leftIntake] = -30;					//Spit out balls from the intake
	motor[rightIntake] = -30;					//Spit out balls from the intake
	wait1Msec(3500);							//Wait until all the balls have been scored
	motor[leftIntake] = 0;						//Stop spitting out balls
	motor[rightIntake] = 0;						//Stop spitting out balls
	setAllMotors(-20);							//Back away from the goal
	wait1Msec(700);								//Wait until we're far enough from the goal to turn around
	setAllMotors(0);							//Stop moving
	while(nMotorEncoder[leftLift]<-200)			//While the lift has not reached its target (the bottom position)
		setAllLiftMotors(-100);					//Move the lift down
	setAllLiftMotors(0);						//Stop moving the lift
	setAllLeftMotors(-50);						//Turn around
	setAllRightMotors(50);						//Turn around
	wait1Msec(1160);							//Wait until we've turned around
	servo[leftHook]=155;						//Raise the hook
	servo[rightHook]=65;						//Raise the hook
	setAllMotors(-30);							//Move backwards towards the goal again
	wait1Msec(1200);							//Wait until we're up against the goal again
	servo[leftHook]=50;							//Lower the hook
	servo[rightHook]=173;						//Lower the hook
	setAllMotors(50);							//Move forward onto the ramp
	wait1Msec(2200);							//Wait until we're on the ramp
	setAllMotors(10);							//Apply enough power to keep us on the ramp for the rest of atonomous
	wait1Msec(30000);							//Keep the program running until atonomous is over
}
