#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     leftWheel1,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel1,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     leftWheel2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightWheel2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     lift1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     lift2,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_1,     pretake,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setAllLeftWheels (int target) {
	motor[leftWheel1] = target;
	motor[leftWheel2] = target;
}

void setAllRightWheels (int target) {
	motor[rightWheel1] = target;
	motor[rightWheel2] = target;
}

void setAllWheels (int target) {
	setAllLeftWheels(target);
	setAllRightWheels(target);
}
void setAllLifts (int target) {
	motor[lift1] = target;
	motor[lift2] = target;
}

void setLift (int target) {
	bool okay = false;
	while(!okay) {
		int test = abs(nMotorEncoder[lift1]);
		int adjTarget = abs(target);
		if(nMotorEncoder[lift1]>target) {
			setAllLifts(100);
		} else if (nMotorEncoder[lift1]<target) {
			setAllLifts(-100);
		} else if ((test>(adjTarget-10)) && (test<(adjTarget+10))) {
			setAllLifts(0);
		}
	}
}


task main()
{

}
